service: SLM-Serverless

#plugins:
#  - serverless-python-requirements
package:
  exclude:
    - node_modules/**
    - __pycache__/**
    - env/**
    - Layer/**
    - package.json
#custom:
#  pythonRequirements:
#    dockerizePip: non-linux
#    pythonBin: /usr/bin/python3
provider:
  name: aws
  runtime: python3.7
  region: us-east-1
  vpc:
    securityGroupIds:
     - sg-2bd77e63
    subnetIds:
     - subnet-3548b569
     - subnet-c14e8fa6
     - subnet-d4ee10fa
     - subnet-4c46c606
     - subnet-daa5b4e5
     - subnet-e04cc5ef
  environment:
    secret_name: SLM/db
    region: ${self:provider.region}
  iamRoleStatements:
    - Effect: "Allow"
      Action: "secretsmanager:GetSecretValue"
      Resource: "arn:aws:secretsmanager:us-east-1:549791063841:secret:SLM/db-a0UJ4B"
  timeout: 60
  memorySize: 128
functions:
  getLogs:
    handler: handler.getLogs
    layers:
      - ${cf:SLM-Serverless-layer-dev.SLMServerlessLayerExport}
  getModules:
    handler: handler.getModules
    layers:
      - ${cf:SLM-Serverless-layer-dev.SLMServerlessLayerExport}
  
